In [ ]:
# https://github.com/laggui/pymultiprocessing-example

In [1]:
from multiprocessing import Process, Queue, Pipe

# Pipe for two-way communication only. Should be faster.
# Queue is a process - and thread - safe implementation with an underlying Pipe

def plot_detections(connection_obj):
    import cv2
    import numpy as np
    import matplotlib.pyplot as plt
    i = 0
    while True:
        try:
            data = connection_obj.recv()
            if i == 0:
                # initialize figure on first message received
                img_size = data
                background = np.ones((img_size[0], img_size[1], img_size[2]), dtype=np.uint8) * 255
                fig = plt.figure()
                disp = plt.imshow(background)
                plt.ion()
            else:
                if isinstance(data, str) and data == "END":
                    print('Last message received')
                    break
                overlay = np.ones((img_size[0], img_size[1], img_size[2]), dtype=np.uint8) * 255
                #print(data)
                [cv2.rectangle(overlay,(x,y),(x+w,y+h),(0,0,255),2) for (x,y,w,h) in data]
                disp.set_data(overlay)
                plt.pause(0.001)
            i = i + 1
        except EOFError:
            print('Communication end')
            break
    
    print('Closing matplotlib')
    if plt.fignum_exists(fig.number):
        plt.close(fig)
    plt.ioff()
    plt.show()
    plt.close('all')

def cam_output_face_detect(connection_obj, flip=True, haar_frontal='data/haarcascade_frontalface_default.xml', haar_second=None):
    import cv2
    import matplotlib.pyplot as plt
    # init cam
    cam = cv2.VideoCapture(0)
    # capture first frame
    ret, frame = cam.read()
    h, w, c = frame.shape
    
    # first send the height and width of image
    connection_obj.send([h, w, c])

    # initialize figure
    fig = plt.figure()
    disp = plt.imshow(frame)
    plt.ion()

    frontal_cascade = cv2.CascadeClassifier(haar_frontal)
    if haar_second:
        second_cascade = cv2.CascadeClassifier(haar_second)

    while True:
        ret, frame = cam.read()
        if flip:
            frame = cv2.flip(frame, 1)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = frontal_cascade.detectMultiScale(gray, 1.05, 6)
        connection_obj.send(faces)
        [cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2) for (x,y,w,h) in faces]
        # if haar_second:
        #     second_faces = second_cascade.detectMultiScale(gray, 1.05, 6)
        #     [cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2) for (x,y,w,h) in second_faces]
        disp.set_data(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
        plt.pause(0.001)
        if not plt.fignum_exists(fig.number):
            break

    plt.ioff()
    plt.show()
    plt.close('all')
    connection_obj.send("END")
    connection_obj.close()



In [2]:
#haar_profile = 'data/haarcascade_profileface.xml'
# create pipe
recv_conn, send_conn = Pipe(duplex=False)

# create new processes
proc_1 = Process(target=cam_output_face_detect, args=(send_conn,))
proc_2 = Process(target=plot_detections, args=(recv_conn,))

# run processes
proc_1.start()
proc_2.start()

# wait until processes finish
proc_1.join()
proc_2.join()

In [4]:
import cv2
import numpy as np
import multiprocessing

cap = cv2.VideoCapture(0)
def get():
        global cap
        cap = cv2.VideoCapture(0)
        return cap

def video(cap):
        _, frame = cap.read()
        frame = cv2.flip(frame, 1)
        return frame


p1 = multiprocessing.Process(target = get)
p1.start()
p1.join()

while True:
    frame = video(cap)
    cv2.imshow("frame", frame)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cv2.waitKey(0)
cv2.destroyAllWindows() 

In [1]:
from multiprocessing import Process
from threading import Thread
import cv2
import numpy as np
import time 


def func_run_forever():
    cap = cv2.VideoCapture(0)
    while(True):
        ret, frame = cap.read()
        cv2.imshow('frame',frame)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

def func_run_once():
    n=0
    while n<10:
        val = np.random.randint(10,size=np.random.randint(10))
        print(val)
        time.sleep(0.25)
        n += 1


p1 = Thread(target=func_run_forever, name="n1")
p2 = Thread(target=func_run_once, name="n2")
p1.start()
p2.start()
p1.join()
p2.join()

[1 1 5 6]
[5 5]
[0 6 7 4 1 2 3 6 8]
[]
[4 5 8 5 6 7 8 1]
[]
[8 1 8]
[1 2]
[2]
[]
